name: CI

on: 
  push:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run Go test
        run: go test ./cfgloader

  build:
    name: Build
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Build
        run: go build ./cfgloader
      - name: Test
        run: go test ./cfgloader