name: Lint

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    name: GoLint
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2