name: Lint

on:
  push:
  pull_request:
  workflow_call:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    name: golint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: ['1.21']
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
