name: Lint

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    name: golint
    strategy:
      matrix:
        go: ['1.21', '1.20']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54