name: Release

on:
  workflow_run:
    types: [completed]
    workflows: [CI]
    branches:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          # Checkout the tag that triggered the workflow.
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Fetch Git tags
        run: git fetch --force --tags

      - name: Set current and previous tag # Workaround, GoReleaser uses 'git-describe' to determine a previous tag.
        run: |
          current_tag='${{ github.event.workflow_run.head_branch }}'
          echo "GORELEASER_CURRENT_TAG=$current_tag" >> $GITHUB_ENV
          previous_tag=$(git -c 'versionsort.suffix=-rc' tag --list --sort=version:refname | grep -Eo '^v[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$' | tail -n 2 | head -n 1)
          echo "GORELEASER_PREVIOUS_TAG=$previous_tag" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}